version: '2'

services:
  mongos:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongos
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=cfg-primary
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_ROOT_PASSWORD=${PASSWORD}
    ports:
      - "${PORT}:27017"

  mongos-2:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongos-2
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=cfg-primary
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_ROOT_PASSWORD=${PASSWORD}

  shard0-primary:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=shard0-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongos
      - MONGODB_ROOT_PASSWORD=${PASSWORD}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_REPLICA_SET_NAME=shard0
    volumes:
      - 'shard0_data:/bitnami'

  shard0-secondary:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    depends_on:
      - shard0-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=shard0-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=shard0-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=${PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_REPLICA_SET_NAME=shard0
    volumes:
      - 'shard0_sec_data:/bitnami'

  shard1-primary:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=shard1-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongos
      - MONGODB_ROOT_PASSWORD=${PASSWORD}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_REPLICA_SET_NAME=shard1
    volumes:
      - 'shard1_data:/bitnami'

  shard1-secondary:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    depends_on:
      - shard1-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=shard1-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=shard1-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=${PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_REPLICA_SET_NAME=shard1
    volumes:
      - 'shard1_sec_data:/bitnami'

  shard2-primary:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=shard2-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongos
      - MONGODB_ROOT_PASSWORD=${PASSWORD}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_REPLICA_SET_NAME=shard2
    volumes:
      - 'shard2_data:/bitnami'

  shard2-secondary:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    depends_on:
      - shard2-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=shard2-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=shard2-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=${PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_REPLICA_SET_NAME=shard2
    volumes:
      - 'shard2_sec_data:/bitnami'

  cfg-primary:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=cfg-primary
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=${PASSWORD}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
    volumes:
      - 'cfg_data:/bitnami'

  cfg-secondary:
    image: docker.io/bitnami/mongodb-sharded:${VERSION}
    depends_on:
      - cfg-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=cfg-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=cfg-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=${PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${REPLICASETKEY}
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_SHARDING_MODE=configsvr
    volumes:
      - 'cfg_sec_data:/bitnami'

volumes:
  shard0_data:
    driver: local
  shard0_sec_data:
    driver: local
  shard1_data:
    driver: local
  shard1_sec_data:
    driver: local
  shard2_data:
    driver: local
  shard2_sec_data:
    driver: local
  cfg_data:
    driver: local
  cfg_sec_data:
    driver: local